{{-- 
==========================================================================
⛔⛔⛔  FILE NOT IN USE / ไฟล์นี้ไม่ได้ใช้งาน  ⛔⛔⛔
==========================================================================
ไฟล์นี้เป็นไฟล์เก่า (Legacy) หรือ Backup ที่ไม่ได้ถูกเรียกใช้งานแล้ว
This file is legacy/backup and is NOT used by the application.

✅ FILE ที่ใช้งานจริงคือ: resources/views/dashboard/index.blade.php
✅ Controller ที่เกี่ยวข้อง: App\Http\Controllers\DashboardController.php

--------------------------------------------------------------------------
DO NOT EDIT THIS FILE / ห้ามแก้ไขไฟล์นี้ (เพราะไม่มีผลอะไร)
==========================================================================
--}}

<div style="text-align: center; padding: 50px; color: red; font-size: 20px; font-weight: bold;">
    ⛔ FILE NOT IN USE ⛔<br>
    Please go to: resources/views/dashboard/index.blade.php
</div>
